DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = cc2650-dht22

all: $(CONTIKI_PROJECT)
CONTIKI_SOURCEFILES += dht22.c

CONTIKI_WITH_IPV6 = 1

CONTIKI = ../../../contiki
include $(CONTIKI)/Makefile.include
